USE WAREHOUSE "COMPUTE_WH";

USE ROLE ACCOUNTADMIN;

USE DATABASE SNOWFLAKE_CI_CD_POC;

insert into SNOWFLAKE_CI_CD_POC.CI_CD_DEMO.GIT_TEST values ('deeptanoy','bhattacharyya');
insert into SNOWFLAKE_CI_CD_POC.CI_CD_DEMO.GIT_TEST values ('deeptanoy','b');
